### ISSUE TITLE
PyPad MySQL Driver (16.04 and 18.04)

### ISSUE THREAD

**Issue by bpm1992** [ElvishArtisan/rivendell#517]
It looks to be some sort of API compatibility issue between version of the Python MYSQL Driver on Ubuntu. This error will occur with PyPad:

Traceback (most recent call last):
  File "/usr/local/lib/rivendell/pypad/pypad_icecast2.py", line 83, in <module>
    rcvr.setConfigFile(sys.argv[3])
  File "/usr/local/lib/python3.5/site-packages/pypad.py", line 843, in setConfigFile
    db=self.__openDb()
  File "/usr/local/lib/python3.5/site-packages/pypad.py", line 802, in __openDb
    charset='utf8mb4')
  File "/usr/lib/python3/dist-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
TypeError: 'password' is an invalid keyword argument for this function

To fix it, the following change can be made in pypad.py on line 802 by changing “password” to “passwd” and changing “database” to “db”.  

    def __openDb(self):
        creds=self.__getDbCredentials()
        return MySQLdb.connect(user=creds[0],passwd=creds[1],
                               host=creds[2],db=creds[3],
                               charset='utf8mb4')

**Comment by ElvishArtisan** [comment]
Please let us know:
The version of Python being used
The version of PyMySQL being used

**Comment by readyformed** [comment]
I can confirm the fix posted by bpm1992 appears to solve PyPad not working on a Mint 19.2 system (similar base to Ubuntu 18.04). Python version "Python 2.7.15+" PyMySQL version unknown.

**Comment by ElvishArtisan** [comment]
Fixed in [master e3dd3ef]. Please test!
