### ISSUE TITLE
rdpadengined spawned as uid 65535

### ISSUE THREAD

**Issue by kernelpanic3** [ElvishArtisan/rivendell#631]
Hi there!

Found a bit of an odd issue just now. When started using rdservice / the systemd script, while everything else runs as root, rdpadengined winds up running under user 65535 / nobody. This breaks Python in fairly exciting ways:

`Failed to import the site module
Traceback (most recent call last):
  File "/usr/lib/python3.6/site.py", line 561, in <module>
    main()
  File "/usr/lib/python3.6/site.py", line 547, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python3.6/site.py", line 288, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python3.6/site.py", line 264, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python3.6/site.py", line 254, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python3.6/sysconfig.py", line 607, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python3.6/sysconfig.py", line 558, in get_config_vars
    _CONFIG_VARS['userbase'] = _getuserbase()
  File "/usr/lib/python3.6/sysconfig.py", line 205, in _getuserbase
    return joinuser("~", ".local")
  File "/usr/lib/python3.6/sysconfig.py", line 184, in joinuser
    return os.path.expanduser(os.path.join(*args))
  File "/usr/lib/python3.6/posixpath.py", line 249, in expanduser
    userhome = pwd.getpwuid(os.getuid()).pw_dir
KeyError: 'getpwuid(): uid not found: 65535'`

I've reproduced this with fresh builds of 3.4.1 on both Ubuntu 18.04 (in a systemd-nspawn container) and Arch (as host).

Thanks in advance for any advice / fix!

**Comment by kernelpanic3** [comment]
As an update, I traced another problem back to the same core issue: when attempting to import files, rdxport.cgi is _also_ being spawned as uid 65535. I was able to work around _this_ for the moment by chmod 777'ing /var/snd. Unfortunately, the kludge my partner and I tried - changing the uid/gid of nobody/nogroup from 65534 to 65535 - just makes it so that rdpadengined crashes as soon as it tries to run a script, and rdxport runs mind-numbingly slow (it seems the script is idling/hanging for some time before actually managing to start the import?).

**Comment by kernelpanic3** [comment]
Just popping in again to say that this is still happening on a testbed I just spun up with 4.0.0beta3int3. I eventually managed to work around it on 3.x by simply running everything as a normal user, but 4.x has added a check against that in rdservice, so I'm a bit stuck ...
