### ISSUE TITLE
Java erros during builds ... what are they?

### ISSUE THREAD

**Issue by alexolivan** [ElvishArtisan/rivendell#698]
This is something I've encountered, I would say, always, in Debian, no matter what while building... but, since it doesn't prevent the packages/binaries to build and work, I didn't cared for.
The issue is that a lot of errors like the following occur while (I would guess) seems that some Java tool tries to parse XML input to render pages, not sure if html or what... here's a sample:

```
[ERROR] FOUserAgent - Invalid property value encountered in column-width="proportional-column-width(1)": org.apache.fop.fo.expr.PropertyException: null:7:971: proportional-column-width() function may only be used when fo:table has table-layout="fixed".; property:'column-width' (See position 7:1211) <org.apache.fop.fo.expr.PropertyException: null:7:971: proportional-column-width() function may only be used when fo:table has table-layout="fixed".; property:'column-width'>org.apache.fop.fo.expr.PropertyException: null:7:971: proportional-column-width() function may only be used when fo:table has table-layout="fixed".; property:'column-width'
	at org.apache.fop.fo.expr.ProportionalColumnWidthFunction.eval(ProportionalColumnWidthFunction.java:61)
	at org.apache.fop.fo.expr.PropertyParser.parsePrimaryExpr(PropertyParser.java:341)
	at org.apache.fop.fo.expr.PropertyParser.parseUnaryExpr(PropertyParser.java:213)
	at org.apache.fop.fo.expr.PropertyParser.parseMultiplicativeExpr(PropertyParser.java:178)
	at org.apache.fop.fo.expr.PropertyParser.parseAdditiveExpr(PropertyParser.java:152)
	at org.apache.fop.fo.expr.PropertyParser.parseProperty(PropertyParser.java:126)
	at org.apache.fop.fo.expr.PropertyParser.parse(PropertyParser.java:92)
	at org.apache.fop.fo.properties.PropertyMaker.make(PropertyMaker.java:438)
	at org.apache.fop.fo.PropertyList.convertAttributeToProperty(PropertyList.java:499)
	at org.apache.fop.fo.PropertyList.addAttributesToList(PropertyList.java:386)
	at org.apache.fop.fo.FObj.processNode(FObj.java:124)
	at org.apache.fop.fo.flow.table.TableFObj.processNode(TableFObj.java:232)
	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.startElement(FOTreeBuilder.java:291)
	at org.apache.fop.fo.FOTreeBuilder.startElement(FOTreeBuilder.java:179)
	at org.apache.xalan.transformer.TransformerIdentityImpl.startElement(TransformerIdentityImpl.java:1073)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.xinclude.XIncludeHandler.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
	at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:293)
	at org.apache.fop.cli.InputHandler.renderTo(InputHandler.java:116)
	at org.apache.fop.cli.Main.startFOP(Main.java:186)
	at org.apache.fop.cli.Main.main(Main.java:217)
```

Rivendell doc part have always been somehow troublesome in my Debian builds (I remember at first, even disable them to build), and the man pages, on the console, look very bad, with huge indentations (this is a common thing with glassplayer and glasscoder) , and I'm thinking that maybe it is related.

Regards.

**Comment by ElvishArtisan** [comment]
The is Apache fop(1) spilling its guts about every little detected problem with its internal state. I've looked for ways to make it be a bit quieter and send output to STDERR only in the event of a _user_ problem being detected (as opposed to an Apache fop(1) developer problem), but to no avail. It is rather ugly, but as you say, it gets the job done.

**Comment by alexolivan** [comment]
> This is Apache fop(1) spilling its guts about every little detected problem with its internal state
:DDDDDDD .... I really loved that one!  :DDDDDDD ...really good one!
