### ISSUE TITLE
RDAirplay 4.0.0beta3 Segfault After Log Chain

### ISSUE THREAD

**Issue by dklann** [ElvishArtisan/rivendell#789]
Version: 4.0.0beta3, git branch _qt5_, commit _a473edf_
Compiled on and running on Ubuntu Studio 20.04, up to date.
Running on ASUS PRIME Z590-A, 16GB RAM, 11th Gen Intel(R) Core(TM) i5-11600

After chaining to the next day's log, RDAirplay encounters a segfault and dies. It appears that the currently playing Cart (at the time of the log chain event) finishes before the crash.

Previous git commits on the same branch (e.g., _bcb22cc_) did not exhibit this behavior.

See the systemd journal at this [pastebin](https://pastebin.com/ZkPeH5Y4) for details.

I have the debug symbols package installed, but I don't really know how to use it to gather more info. Any help is appreciated.

**Comment by alexolivan** [comment]
Yesterday I found my 24/7 VM without RDAirplay missing ... Its so stable (no crash ever, from my early 3.X tests!) that I didn't though for a moment on a crash... however, that makes full sense with your issue!

I'm gonna switch it to a console on debug to have a backtrace if it crashes.

**Comment by dklann** [comment]
I also managed to run rdairplay with GDB. Similar stack trace as @alexolivan posted when it encountered the segfault. For the record here is the stack trace:
```Thread 1 "rdairplay" received signal SIGSEGV, Segmentation fault.
RDPlayDeck::cut (this=this@entry=0x0) at rdplay_deck.cpp:266
266     rdplay_deck.cpp: No such file or directory.
(gdb) bt
#0  RDPlayDeck::cut (this=this@entry=0x0) at rdplay_deck.cpp:266
#1  0x00007ffff7892245 in RDLogPlay::CleanupEvent (this=this@entry=0x5555556bdf70, id=id@entry=497) at rdlogplay.cpp:2269
#2  0x00007ffff789bc17 in RDLogPlay::Stopped (this=0x5555556bdf70, id=497) at rdlogplay.cpp:2912
#3  0x00007ffff583d1d0 in QMetaObject::activate(QObject*, int, int, void**) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007ffff7a18240 in RDPlayDeck::stateChanged (this=<optimized out>, _t1=<optimized out>, _t2=<optimized out>) at moc_rdplay_deck.cpp:295
#5  0x00007ffff583d1d0 in QMetaObject::activate(QObject*, int, int, void**) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff7a0a3e5 in RDCae::playStopped (this=this@entry=0x555555c7e790, _t1=<optimized out>) at moc_rdcae.cpp:345
#7  0x00007ffff76f5b89 in RDCae::DispatchCommand (this=0x555555c7e790, cmd=0x7fffffffce80) at rdcae.cpp:569
#8  0x00007ffff76f80ae in RDCae::readyData (this=this@entry=0x555555c7e790, stream=stream@entry=0x0, handle=handle@entry=0x0, name=...) at rdcae.cpp:442
#9  0x00007ffff76f8652 in RDCae::readyData (this=0x555555c7e790) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:699
#10 0x00007ffff7a0aa33 in RDCae::qt_static_metacall (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>) at moc_rdcae.cpp:158
#11 0x00007ffff583d1d0 in QMetaObject::activate(QObject*, int, int, void**) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff584a3ee in QTimer::timeout(QTimer::QPrivateSignal) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007ffff583dbc5 in QObject::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff643aa66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff64440f0 in QApplication::notify(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff581180a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff5868780 in QTimerInfoList::activateTimers() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007ffff586906c in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007ffff40a317d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007ffff40a3400 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007ffff40a34a3 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007ffff5869435 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007ffff58103ab in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00007ffff5818116 in QCoreApplication::exec() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x0000555555580915 in main (argc=<optimized out>, argv=<optimized out>) at rdairplay.cpp:2231
```

**Comment by ElvishArtisan** [comment]
Fixed in 2fbc9681. Please test.

**Comment by dklann** [comment]
Confirmed working here! Thanks for the fix Fred!

**Comment by ElvishArtisan** [comment]
Cool. Thank you both for the very detailed and informative bug reports!
