### ISSUE TITLE
RDLogManager 4.0.0beta3 in "Report Mode" Crashes When Run Without GUI

### ISSUE THREAD

**Issue by dklann** [ElvishArtisan/rivendell#792]
This looks similar to the rdclilogedit(1) crash under similar circumstances. In this case I'm running `rdlogmanager -r REPORT_NAME -s Production` from a script; with no DISPLAY environment variable. I see in _rdlogmanager/commandline_ops.cpp_ that `RunReportOperation` calls `QApplication`. Maybe should this be `QCoreApplication`?

Stack trace for the record:
```#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f0823b6e859 in __GI_abort () at abort.c:79
#2  0x00007f0824251aad in QMessageLogger::fatal(char const*, ...) const () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007f0824a447ae in QGuiApplicationPrivate::createPlatformIntegration() () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#4  0x00007f0824a45708 in QGuiApplicationPrivate::createEventDispatcher() () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#5  0x00007f0824458f55 in QCoreApplicationPrivate::init() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f0824a47543 in QGuiApplicationPrivate::init() () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#7  0x00007f08250823bd in QApplicationPrivate::init() () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x000056001c9932d0 in RunReportOperation (argc=<optimized out>, argv=<optimized out>, rptname=..., protect_existing=<optimized out>, start_offset=0, end_offset=0) at commandline_ops.cpp:39
#9  0x000056001c98cbdf in main (argc=<optimized out>, argv=0x7ffe87e77448) at rdlogmanager.cpp:390```

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 91345cb. Please test.

**Comment by dklann** [comment]
Confirmed working.

**Comment by ElvishArtisan** [comment]
And the beat goes on...

Thank you!
